cartonnagecrea_produits:
    resource: "@cartonnagecreaProduitsBundle/Resources/config/routing.yml"
    prefix:   /

# C:\wamp\www\project_Cnam_Symfony2.8\cartonnagecrea\app\config\routing.yml

cartonnagecrea_client:
    resource: "@cartonnagecreaClientBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"